project:
  type: website
  output-dir: docs

website:
  title: "Veronika Lohmanova"
  navbar:
    right:
      - about.qmd
  draft-mode:  gone
  favicon: favicon.ico
format:
  html:
    theme:
      - flatly
    css: styles.css

editor: visual


