project:
  type: website
  output-dir: docs

website:
  title: "Veronika Lohmanova"
  navbar:
    right:
      - about.qmd
      - blog_page.qmd
  draft-mode: unlinked
  
format:
  html:
    theme:
      - flatly
    css: styles.css

editor: visual


