---
title: "Moonlight, Venice"
description: "What point of us, creatures, monstrous atrocities, celestial beings, walking on the water, if we cannot fly away to the sun nor drown at the bottom?"
author: "Veronika Lohmanova"
date: "04/22/2024"
categories:
  - "Creative writing"
draft: true
---

With a bang, the door blew open. I knew it would happen. Before me stood a young lady officer, without trembling pointing her gun straight to my heart.

Even behind my mask I could not hide the grin – her uniform was smitten and had a bit of dirt on it – seems to be the result of a long pursuit. Reflected in her eyes, the moonlight was like a hawk’s screech just the second before it dived to its prey. The hunt. Without hesitation. Without even the smallest twitch.

Yet unlike her, my heart was trembling, it was smitten just like her form, dirtied through ages. My hands were moving not by mind, but by soul, itself, slowly taking off the mask from the face, from the mind, from the heart. It was the feeling of hot, yet cold to the bones fresh waterfall washing all that I had brought along the way. It did not stop by my hand, lips and tongue continued what my subconsciousness intended. I spoke words, spoke truths, spoke lies in the language that was long from gone, yet it was the first time I decided to break the water's surface, to try to reach beyond, to try to reach what I see on the other side of the glasslike surface. I simply begged via pronouncing the words, *Exorsa please just talk to me*.

------------------------------------------------------------------------

*I see how you did it* Exorsa grinned.

I pushed away the curtain I was hiding behind. My presence was found out; I couldn't hide anymore.

The middle of London was loud as ever, cars roaring and endlessly moving from and to somewhere, newspaper dealers catching the attention of sirs and madams. Servants could be heard from the first floor preparing for the tea. The time when the city seems to be the most alive. A middle-aged woman, sitting by herself in a light gown, as everything around her is like a distant sea, drilled her sight onto the unfinished glass of red wine that was in front of her.

*How much time do I have left, Mors?* She looked at me with a corner of her eye.

I looked at my wristwatch, *Around a quarter of a minute by my calculations*, I replied.

*Hah*, she almost let a laugh out, *next time I will be the one to kill you first.*

The gaze at the glass of wine averted. Her lifeless body finally became free of tension. With every step to her, it was as if I was drawn deeper and deeper, water crushing my lungs, without daylight nor moonlight reaching my eyes. I caringly took her into my arms and carefully, not to destroy her precious hairstyle, laid her down on the sofa that was next to the writing table. Her lifeless body touched the sofa. There was a small coffee table with a vase of roses behind me. I took one and put it in her hands. I could not hold it anymore; I fell onto my knees in front of her. Again, again, again. Is it the fate of us, cursed by stars, to hunt each other without a break? To hunt the only one who shares your curse. The only one who remembers you. The only one who notices your existence. To kill, to be killed and reborn again. Is that what humans call fate, that sea I am drowning in? What point of us, creatures, monstrous atrocities, celestial beings, walking on the water, if we cannot fly away to the sun nor drown at the bottom?

Humans say fate is not changeable nor unchangeable. They say it is choices that we make to get to that certain point. Then, can I *change*? Can I truly live? I stood up and rushed to her writing table. My arms stretched to the glass of wine she had left behind and I gulped it down, emptying it, not leaving even the smallest drop.

------------------------------------------------------------------------

A full moon arose from behind the buildings of Venice. Two people, standing in the middle of the canal, on the water seemed to be distant from each other, yet close. One had a pistol in her hands, the other – the mask.

Exorsa thought, how the second before cornered person moved so fast, almost slipped through the hands. It seemed he partially awakened the celestial power this time too. Now, his facial expression appeared somewhat strange as well as a waste of time. Nonetheless, she continued to stand the aggressive stance with her finger on the trigger.

Gunshot. Miss. Another gunshot. Another miss. Exorsa became more alert. It was unheard of for Mors to dodge bullets, he deflects them.

*Listen to what I have to say.* Mors started talking again. One more gunshot, one more miss. *Maybe it is not time to kill each other* - he calmly continued as if it was a casual chat between two neighbours on Sunday morning - *is it not the time to stop the cycle? Don’t you feel the same way I do, my only guiding star in the sea of eternity?*

One more gunshot, one more miss. With a frozen stance, not relieving the tension even in the smallest muscle, Exorsa's aggressive eyes were for a second changed to lifelessness. Dark as the bottom of the sea. Expressionless. To not drag the circus out, she in the end decided to answer, *I do not have any feelings nor emotions. From the beginning, I got rid of them as I understood that I would not last otherwise. I exist for one sole reason, the mission that was given by the ones who summoned us to eternally chase and destroy you.*

A tear. A tear from my face that was once again hidden by the mask. When the tear reached the water’s surface, the fired bullet was lost in the fog. The masked man disappeared as a mirage. Only a young officer remained on empty Venice streets, illuminated by moonlight playing in the haze.
