---
title: "A glass of brandy and a sandwich"
description: "There, April and February are waiting for me. Once again, spring had come."
author: "Veronika Lohmanova"
date: "02/01/2024"
categories:
  - "Creative writing"
draft: true
---

I am not sure when it all started.

Was it the day April was lost? Was it the day February was bedridden? Or was it the day Big Storm took the lives of my parents? No, my heart tells me it was the moment when my eyes caught an old book of Greek legends. It was falling apart, yet still safely kept on the shelf in February’s house. Books are precious here in any condition. We are a small island in the middle of nowhere that many say is cursed. And I started to agree.

We were three, a loveful family. Only my tears remember the last warm morning we had. My beloved father whose strange sense of humour did not have a limit. My beloved mother who wholeheartedly laughed at each awkward joke of father.

We were three, a joyful, even mischievous trio. We were the ones who could flip the land into the sky, the ones, who could be lectured by every dweller on our island in one day. Looking back, it is really funny how our names aligned - February, March and April. February lived on the other side of the island. He was the oldest, the calmest and a rational one in our trio. However, when the fire was started by me and April, his rationality was erased, the fire in his eyes was inextinguishable. April was a year younger than me and lived next door. She was our treasure, the one I deeply cherished and loved. Even to this day, every time I open my eyes I still regret unsaid words. I cannot get from my memory her dark blue eyes, deep as the sea, her a bit fluffy hair, light as the highest cloud, and the laugh, that wind so finely carried to my heart.

At 12 years of age, April just vanished. Through sleepless nights the whole island desperately searched for her, only to find her lifeless body wave-borne on the next full moon. It was the day when the cry of my soul was heard on ships in the sea. At 15 years of age, February caught mild inflammation. To us, islanders, that means a straight road to death as we lack medicine here. Only my tears remember how much I cried by the side of my bedridden friend as he was slowly passing away. Even during his last moments, he smiled at me as his fire in the eyes flicked. His soul longed for peace, for meeting April again. He loved her too.

What have I done wrong for God to take them from me in such a cruel way? This island is cursed. It is a cage that is tearing me from inside and outside, driving me to madness.

The Memory Night is a night when we light up the bonfire, the flames of which dance higher than our heads, as a memory of whom we have lost. The last time was when I visited February’s grandmother to pick up the wood, I caught a glimpse of the nearly fallen-apart book on the bookshelf. Was it God’s will or my heart and soul, I was drawn to it. The elderly lady, who has been taking care of me since my parents were murdered by the storm, allowed me to take that book.

I cannot say whether it was the blessed or cursed book.

The story of Icarus, the one who found hope, the muse, found what to stretch for and what to live for, even when being confined in the cold labyrinth, even when it meant his death. That day I could not avert my gaze from the yellow sun, which closer to daybreak changed to orange and reddish and then to the flames of the Memory Night. My mind had hopelessly wandered off to the world of ancient king Minos and Minotaurus, the world of poetry cruelty, the world where people can fly.

Could not fit myself on the bed, could not close my eyes, could not loosen up. The witching hour was upon me. How far was the shore? How far was the bed built on the lake of tears? How far was God's forgotten heaven? When I came to my senses, I was already at the cliff. The cliff, magnificent yet frightening, beckoned me. Beckoned me to try being Icarus, beckoned me to lose everything I had, beckoned me to cut everything tying me to this land.

When I was ready to start my flight, the wind, cruel just as my life, blew into my face, forcing my eyes to open. The rustle of leaves. The crack of trees. The crying sounds of birds. It was the same. The second coming of Big Storm, from which onward my warm life became a cold one.

My mind was still on the edge of the cliff yet my legs carried me further and further from it. I could not see where I was running - the rain obstructed my vision, and my tears mixed with raindrops made it even harder, both physically and mentally. I was lost, I did not know where to turn, I did not know where to scarce. From my mother's and father's gaze. From February’s and from April’s. I could not see the path before me.

The next day, my uncle found me clogged in a corner. I did not want to see and did not want to be seen. My uncle pulled back my hands from my face and got me on my feet.

“Nightmares again? ” he somewhat shouted at me. It was not a shout driven by anger, but a shout out of concern.

I backed up to the wall behind me and collapsed again. Yes, I know, I am selfish. I am not the only one who lost their loved ones. Uncle lost his younger brother. Grandma Amanda lost his grandson. The whole island lost the spring, together with April.

My tears started overflowing. “I am sorry,” crushing my throat I spoke. “I am sorry, I am sorry, I … I cannot anymore…” I hushed. Uncle bent over to me and put his large and rough palm on my shoulder.

“I am the one who is sorry, March. I know how hard life is for you… Please…”

his tears started coming out.

“Please… Look at me… ” he hushed.

I turned my face from the floor to him. And there I saw… I saw the same expression as mine, the helpless boy, who had lost his sun.

“I am the one who you still have, yet I cannot take care of you properly… I am ashamed as a sailor, that I conquer the seas in the hope of finding new light, yet cannot be where I am needed… There was a storm in the sea and I could not even be here, this year’s Memory Night…”

Somewhere the melody started playing. I turned around. There was my father sitting in the kitchen with a guitar, playing the song he most enjoyed. The song that he had written for my mother. Even after decades, she remembers each note, each word. I hear the knock on the door. There, April and February are waiting for me. Once again, spring had come. Just as my father’s guitar strokes became faster, running wild for culmination, the haze started clearing up.

I woke up.

Still sleepy, I slid into my slippers. Slowly, step by step descending the staircase, I noticed my smiling uncle.

“Happy birthday, March! ” his teeth sparked between the lips.

“You have made it!” I could not hold in the impulse and ran to him, opening my arms for a hug.

“Of course, I am the captain now. I can take weekends almost any time now.”

He patted me on my head and my tears started coming out. “While I did not forget,” he hastily turned around.

In his hands was the guitar. The same guitar I saw in the dream.

“When you were born, we were on the 9th cloud” - he softly said - “Your father, my younger brother, when he looked into your eyes for the first time, had said that you are as the melody of life. He mentioned gifting you his favourite guitar, the one that your mother painted over when they were younger, on your 16th birthday.”

My knees buckled. I collapsed to the ground. It was the first time I felt the warm rays of the sunshine that I had lost a long time ago. The music from my dream was meant to be heard. I felt I was not alone, I felt that I was the carrier of voices, melodies and suns of the ones, who were lost.

The blessed instrument was bestowed upon me. I found the determination to master it, being that my wings would bring me to the sun. After that, my uncle had always brought me more books about the music. Sitting on a dune, watching the yellow sun become orange and reddish, resembling the Memory Nights, my fingers pickled on different sounds. It was as if my beloved father joked, my mother laughed, February murmured and April chuckled. It was as if my lost family was right beside me.

After a couple of years, my uncle said with pleasure that he would get married and live on the continent. My tears, not of pain, but of joy, had flooded me once again. I was truly joyous that my uncle had the family life he longed for after all these years. Being the man of the seas, I thought it would be challenging for him to settle down, however, thank God, I was wrong. He offered me to come with him, with an adventurous sparkle in his eyes, to come to the outside world. That startled me.

“I… I.. Cannot, I am sorry… There is the place I belong, where the voices of my beloved and lost ones are…”

Uncle regretfully looked at me, yet acknowledged my decision. “If you are to change your decision,” said he, “we leave at noon”.

I immersed myself into everyday chores - washing clothes and dishes, and tidying up the house. When I was sweeping the floor and singing the song of my father and mother, I heard a melody. I turned around. April was playing the guitar. I could not believe it. She noticed me noticing her, as she softly put it on the table and suddenly ran out of the house, swinging the door open. All I could do was to follow her, as fast as possible. She ran through the gardens. Even hurriedly following her, I could not reach her - she was not slowing down. Through the gardens. Through the forest. We ran off to the shore. The wind, messing with my eyes, once again covered my vision. I could not see, but moreover, I could not stop. The warm sand under my feet suddenly changed into a cold water surface. The haze in my head cleared, and I managed to open my eyes. “Wait!” I shouted. April was nowhere to be found. Again. Only the uncle’s frigate was seen, slowly gliding from me, realising the sails. Yet I didn’t stop. Footprints left behind were just like the bridge. Bridge to the yellow sun. Not orange nor reddish, not in colours of flames, but yellow. It was my sun, not of my guitar, the sun I, the Icarus with wings, am yet to fly to.

As my feet moved forward, as my heartbeat felt warmer, as I was in the middle of a blessed flight, notes played by me reached the ears of others. The voices of my dear ones, the voice of my own were being heard. With the last chord, with the first warm morning, with the first Memory Night, with the fire in my heart and soul, my tears, slowly creeping down my face, joined the billions of others dispersed over the whole world just as stars so far away.
