---
title: "A glass of brandy and a sandwich"
description: "And way down we go…"
author: "Veronika Lohmanova"
date: "05/17/2024"
categories:
  - "Creative writing"
---


I remember the smell of the rain. I remember the late August, the time when Bakewell bloomed. I remember sitting on the windowsill in the library in our house with a slightly open window seeing a garden full of greens being refreshed as if Eden grew anew and small birds singing swiftly. I remember and want to remember for eternity yet curse the moment I picked up a worn-down book about the adventures of Sherlock Holmes.

The mystery. The satisfaction of a solved case and glass of brandy. The thrill of chasing and bringing downfall to criminal masterminds and Lords of the underworld.  It hung onto me, as a shadow following me everywhere I went, making me long for it. I felt empowered and aspired to become a resident of 221B Baker Street one day. Oh, that was naïve of me.  

My father was a book illustrator, mother was a glass artisan. It is ironic: glass can be melted and transformed into a smooth shape, yet it can shatter with one breath. We lived near Bakewell, a small town in the United Kingdom. Moved to Rotherham and studied criminology at the University of Derby for my bachelor's. And here I am now, in the kitchen of a golf course and small inn in Hagavollur, Iceland making toasts. At least somewhere my strange talent is needed. Next to me stood my childhood best friend, Simon Ashgrey.

Back in Bakewell, we were known as the Ash duo. My grey hair colour and his surname brought more trouble to the lives of neighbours than you can imagine. But, you know, at the end of the day we were loved by everyone. To my demise, Simon’s family moved to Iceland two months before starting high school. It was said that they needed to help the old aunt to run her business there. We later found out that it was an inn and golf course. As the zone was degraded there, we would often exchange letters with him, ciphering and deciphering messages between ourselves.

_Oh, Father tell me …_

The inn opened for golfers to have a nice breakfast before handing to the range for warmup. It is so early in the morning, that you can see the sun only slightly, it is still hidden behind the horizon. It is fairly cold outside even now, in early September. The inn is decorated with wood and has a fireplace that makes it cosy; you can see mist covering the valley through panoramic windows. Simon turned on his morning playlist to welcome early birds inside the dining area. 

_… do we get what we deserve?_

_We?_ Yesterday’s incident dug up memories that I begged on my knees to forget and thought _we?_ 

The tide that I had been fighting with for the last month had engulfed me once again. My face started uncontrollably twitching and my mouth laughing. I tried to stop and hide my face behind my hands, however, as a result, I was tearing apart my face and ash-coloured hair. I started to lose balance and hit the cabinet behind me, falling and losing myself in hysteria. 

_We? We? We? We? We? We? We? We? We? We? We? We? We? We? We? We?..._ I felt as if my consciousness started to flee somewhere out of my body. I could not control and handle myself anymore.

After university, I interned in a police investigation unit. There, a naïve young boy from Bakewell who looked up to the one and only one Sherlock Holmes was hit by utterly disgusting reality. Murders. Corpse. Incomprehensible reasons. Bells of Chapel. Black clothes. Cry of victims' loved ones. Wake up. Murder. Corpses. _Without a reason, just for fun_, they said straight to my face before the court. Bells of chapel…

Since the beginning of the long-awaited era of my life, I started to doubt myself. _Is this the world we all live in?_ What did I even want? Is it alright that I had so much inspiration growing up? Studies at university were heavy, but fine enough. Then when have I lost my _thrill_? When have I lost myself? Yes, that’s right. The moment you see the tears of everyone around the fallen one and the wicked fire in the eyes of those who were guilty. Those, who will not understand their sins and atone for them. Slowly, but steadily I started to lose my belief in our world, and my will to continue. Yet hours turned to days, days turned to months, months to seasons and seasons to a couple of years. I was working full-time and rose by several ranks. My every step was becoming heavier minute by minute.

Yes, that’s right. The moment you become one the mourning. I don’t remember that day vividly. A call for an investigation team was made. Me and my colleagues were dispatched. We arrived at the scene. I put on gloves and lifted the veil covering the victim’s face. The uncovered face was of my younger brother, Arthur. Further, my memory is in haze. Someone spotted a suspicious individual. The chase and the catch. The court. His smirk. The judge let him go. The grit of my teeth and an unsettling feeling in my chest. - _No, no, no, no, no, no, no, no, no, no, no, no, no…_

_Art, my brother!_ I screamed. Younger by three years, moved to be closer to me while attending the university. The proud legacy of the Ash duo. On the first day of new life, violently taken out. Killer on the free run, no punishment. Someone slapped me, _Aug, wake up!_ Cold water poured onto my head and face, _August Johnson, stood up and served Detective Fahrer her sandwich!_

My boss insisted that I take a longer break to _reinforce my mental health_. After Art’s death, I took quite a hit. Simon came forward and offered to take me with him for some time. He needed additional hands and I needed someone to lean on. You can see how he put up with me and my hecticness that splurged and fought with my sanity, yet you can see pity and anger. Anger with himself that he cannot help me, that’s the fight for me and only me.

_Whoa, we get what we deserve…_

Cold water as if pressed reset to my mind. At least I managed to get up and give Claire her almost burned down if not for Simon a hot sandwich. Detective Claire Fahrer. Yesterday in the early opening hours a lady in all pink attire nearly smashed through the front door of the reception. She spotted a dead man lying in the middle of the hole and ran to us. We closed the golf course for now.  Police took half a day to bring all the equipment required for the record and investigation. Detective Fahrer was named as the main investigator on this case as police concluded that there was a chance that it was an intentional murder of millionaire Mr Seman, age 58 as half of his head was smashed with a blunt object. There were no initial leads, so Claire said she would stay for a couple of days to gather all the information she could. Simon seemed to be on the edge as well and his family’s business name is now tarnished with blood.

While serving the sandwich I noticed something different in the scenery outside. Beasts - bulls, bears and everything in between – with fog in place of their flesh. Something flinched in memory, it was as if beasts were a mere parade in front of true calamity. Everybody was glued to the action unfolding before their shocked eyes. The sky and clouds were strangely coloured as well. You look up to the sky and you know that you will be no more. Without a doubt, it was the end—the beginning of the end and the end of the beginning. I touched my lips – I unconsciously smirked. The same smirk that that killer had. Is it not the moment we had waited for?

_And way down we go…_