---
title: "Brother's lantern: Part 1"
description: "Amongst darkest shadows I saw a light of red latern."
author: "Veronika Lohmanova"
date: "02/28/2024"
categories:
  - "Creative writing"
draft: true
---

The trains doors slid open.

Usually, train stations have this announcement that proudly warns people to mind the gap between the platform and the train. However, on this station, there was no platform at all. I took a step forward. It felt a bit uncomfortable. It was not as if I was going into the unknown, but instead, something from my past was grabbing me and dragging me closer.

“Professor Shui, where should we head next?” asked Patrick. I felt relieved, as with me were my students from the lab. I needed someone to hold me the moment I go crazy. Three students joined me on the expedition to the Yangmingshan.

When we stepped out of the train the sun was at its zenith, and the sky was clear. We could hear bird’s songs as they flew above. There was an adventurous atmosphere hanging around students -Patrick, Alice and Andrew. When I think back, I find it quite ironic – behind me were smiles and laughs, the warmness - and I headed and directed them in the opposite direction. Then I had a hunch, that the night would bring the frost to their lives.

“There is a small town within fifteen minutes of walking. We need to go through the valley so it is that direction,” waking up from deep thoughts I replied and pointed to the right of the crossroad.

Fifteen minutes passed with flying colours: Patrick, being energetic and positive, started to croon. Alice joined in and after a couple of stanzas. Andrew, a more reserved person, gave up and joined them.

Elevated by singing songs we passed fields of various crops at the bottom of the valley. We paced faster when we saw the village in front of us.

We wandered around the village. We had been travelling for a while and as a matter of fact, at some point everybody got hungry. Without further ado, we went into the first open eatery we saw. We chose a delightful spot in the corner by the window, where breathtaking scenery made us feel otherworldly aesthetical pleasure.

An old lady who was serving the food stared at us in the beginning. I thought it probably was because of students were foreigners. Hoped so. Her face softened when I asked her how high the clouds were today. The question itself might seem puzzling or senseless, nevertheless, in the past, it was a fast way to check the state of the village. Deep down I desired that at least this tradition had lived on.

“The clouds are low. So low that we cannot see ourselves,” she answered, “so low, that I cannot distinguish you and the ghost. Why do you know the language art of clouds?”

Because I am who created it, I wanted to say yet hesitated. Instead, I decided to say: “Because it is part of my past.”

“May the wind guide and water protect you during your wanders and travels,” encouragingly smiled she. We thanked her for the food and set off. Food made my inner child that was hidden somewhere deep down cry. Tears of the past moments that I cannot return to. The nostalgia. The constraint. Only with ageing has my perception shifted to favouring every second we live. Every breath. Every tick of the never-stopping clock. It is admiration that I feel towards Patrick, Alice and Andrew. The sprout of youth. I felt that only once in lieu of giving the wings and the sky to roam in, ripped me of everything I had. Nevertheless, it was my choice. My choice to cast aside everything I hated. It was out of my sight that I would be forced to abandon what I cherish as well.

When we got to the foot of the mountain it was already golden hour. We needed to find a place to camp the night. Stopping before the mountain and beholding its overwhelming aura, suddenly, out of my head one memory jumped out and I started rushingly chanting mantra. That mantra was given to the mountain god, who oversees whoever steps onto it. That mantra was one more thing that melancholically echoed in my heart.

Alice looked at me with a sprinkle of revelation. At some point, I believed I could not surprise them anymore.

With the mantra’s last word, I took a deep breath. It was the feeling of a strong need to do so both physically and mentally.

TBC Part 1
